version: '2.1'
# This scenario is loosely based on the official tutorial 5
# https://www.rabbitmq.com/tutorials/tutorial-five-java.html

services:
  rabbit:
    image: rabbitmq:management-alpine
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
      - '15671:15671'
      - '15672:15672'
      - '25672:25672'
    healthcheck:
      test: ["CMD", "wget", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 15
  direct-producer:
    build:
      context: .
      dockerfile: producer.Dockerfile
    image: permalost/rabbit-tutorials-producer
    environment:
      - RABBIT_HOST=rabbit
      - EXCHANGE_NAME=direct_logs
      - EXCHANGE_TYPE=direct
      - ROUTING=severity
      - MESSAGE=randomPhrase
      - TIMING=secondDelay
    depends_on:
      rabbit:
        condition: service_healthy
  direct-consumer-fatal:
    build:
      context: .
      dockerfile: consumer.Dockerfile
    image: permalost/rabbit-tutorials-consumer
    environment:
      - RABBIT_HOST=rabbit
      - EXCHANGE_NAME=direct_logs
      - EXCHANGE_TYPE=direct
      - BINDING_KEYS=FATAL
    depends_on:
      rabbit:
        condition: service_healthy
  direct-consumer-warning:
    build:
      context: .
      dockerfile: consumer.Dockerfile
    image: permalost/rabbit-tutorials-consumer
    environment:
      - RABBIT_HOST=rabbit
      - EXCHANGE_NAME=direct_logs
      - EXCHANGE_TYPE=direct
      - BINDING_KEYS=WARNING
    depends_on:
      rabbit:
        condition: service_healthy
