version: '2.3'
# This scenario is loosely based on the official tutorial 5
# https://www.rabbitmq.com/tutorials/tutorial-five-java.html

services:
  rabbit:
    image: rabbitmq:management-alpine
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
      - '15671:15671'
      - '15672:15672'
      - '25672:25672'
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 20s

  topics-producer:
    build:
      context: .
      dockerfile: producer.Dockerfile
    image: permalost/rabbit-tutorials-producer
    environment:
      - RABBIT_SERVERS=rabbit
      - EXCHANGE_NAME=topic_logs
      - EXCHANGE_TYPE=topic
      - TIMING=secondDelay
      - MESSAGE=randomPhrase
      - ROUTING=facilityseverity
    depends_on:
      rabbit:
        condition: service_healthy
  topics-consumer-hq-and-info:
    build:
      context: .
      dockerfile: consumer.Dockerfile
    image: permalost/rabbit-tutorials-consumer
    environment:
      - RABBIT_SERVERS=rabbit
      - EXCHANGE_NAME=topic_logs
      - EXCHANGE_TYPE=topic
      - BINDING_KEYS=HQ.INFO
    depends_on:
      rabbit:
        condition: service_healthy
  topics-consumer-warnings:
    build:
      context: .
      dockerfile: consumer.Dockerfile
    image: permalost/rabbit-tutorials-consumer
    environment:
      - RABBIT_SERVERS=rabbit
      - EXCHANGE_NAME=topic_logs
      - EXCHANGE_TYPE=topic
      - BINDING_KEYS=*.WARNING
    depends_on:
      rabbit:
        condition: service_healthy
  topics-consumer-uswest:
    build:
      context: .
      dockerfile: consumer.Dockerfile
    image: permalost/rabbit-tutorials-consumer
    environment:
      - RABBIT_SERVERS=rabbit
      - EXCHANGE_NAME=topic_logs
      - EXCHANGE_TYPE=topic
      - BINDING_KEYS=USWEST.*
    depends_on:
      rabbit:
        condition: service_healthy
  topics-consumer-hq-or-fatal:
    build:
      context: .
      dockerfile: consumer.Dockerfile
    image: permalost/rabbit-tutorials-consumer
    environment:
      - RABBIT_SERVERS=rabbit
      - EXCHANGE_NAME=topic_logs
      - EXCHANGE_TYPE=topic
      - BINDING_KEYS=HQ.*,*.FATAL
    depends_on:
      rabbit:
        condition: service_healthy
