version: '2.3'

services:
  rabbit:
    image: rabbitmq:management-alpine
    expose:
      - '4369'
      - '5671'
      - '5672'
      - '15671'
      - '25672'
    ports:
      - '15672:15672'
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 20s

  producer:
    build:
      context: .
      dockerfile: producer.Dockerfile
    image: permalost/rabbit-tutorials-producer
    env_file:
      - .${TUTORIAL}.env
    depends_on:
      rabbit:
        condition: service_healthy
  consumer:
    build:
      context: .
      dockerfile: consumer.Dockerfile
    image: permalost/rabbit-tutorials-consumer
    env_file:
      - .${TUTORIAL}.env
    depends_on:
      rabbit:
        condition: service_healthy
