version: '2.3'
# This scenario is loosely based on the official tutorial 5
# https://www.rabbitmq.com/tutorials/tutorial-five-java.html

services:
  rabbit:
    image: rabbitmq:management-alpine
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
      - '15671:15671'
      - '15672:15672'
      - '25672:25672'
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 20s

  logs-producer:
    build:
      context: .
      dockerfile: producer.Dockerfile
    image: permalost/rabbit-tutorials-producer
    environment:
      - RABBIT_SERVERS=rabbit
      - EXCHANGE_NAME=logs
      - EXCHANGE_TYPE=fanout
      - ROUTING=severity
      - MESSAGE=randomPhrase
      - TIMING=secondDelay
    depends_on:
      rabbit:
        condition: service_healthy
  logs-consumer1:
    build:
      context: .
      dockerfile: consumer.Dockerfile
    image: permalost/rabbit-tutorials-consumer
    environment:
      - RABBIT_SERVERS=rabbit
      - EXCHANGE_NAME=logs
      - EXCHANGE_TYPE=fanout
    depends_on:
      rabbit:
        condition: service_healthy
  logs-consumer2:
    build:
      context: .
      dockerfile: consumer.Dockerfile
    image: permalost/rabbit-tutorials-consumer
    environment:
      - RABBIT_SERVERS=rabbit
      - EXCHANGE_NAME=logs
      - EXCHANGE_TYPE=fanout
    depends_on:
      rabbit:
        condition: service_healthy
